#!/bin/bash

mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.6 --transvel 0.5
mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.7 --transvel 0.5
mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.8 --transvel 0.5
mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.9 --transvel 0.5
mpiexec amuse mw_m31_merger.py --test --solar --radvel 1.0 --transvel 0.5