#!/bin/bash

mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.5 --transvel 0.6
mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.5 --transvel 0.7
mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.5 --transvel 0.8
mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.5 --transvel 0.9
mpiexec amuse mw_m31_merger.py --test --solar --radvel 0.5 --transvel 1.0